name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Lint/test backend plugin (minimal)
        run: |
          python3 -m venv venv && . venv/bin/activate
          pip install -r supervisor/requirements.txt
          python -m pyflakes supervisor || true

      - name: Build and push Docker images
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/xploitrum-frontend:latest
            ghcr.io/${{ github.repository_owner }}/xploitrum-supervisor:latest
